### ISSUE TITLE
Display popular/recent posts at the end of current one

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#103]

**Comment by rauldiazpoblete** [comment]
Actualmente ya aparece una sección de 'Artículos relacionados' al final de un post. ¿Queremos añadir otra sección de 'Artículos destacados'?

**Comment by EvaBelmonte** [comment]
Creo que este issue se refería a que, cuando acabes de leer y llegues al final de la página, te proponga pasar a otro artículo con un pop up o similares, para intentar retener al lector más rato.

**Comment by rauldiazpoblete** [comment]
Modificaremos el diseño de los articulos relacionados para destacarlos más y que cumplan la misión de retener al lector
