### ISSUE TITLE
Votaciones en fotos

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#162]

**Comment by rauldiazpoblete** [comment]
La idea es que el usuario vote X puntos y usemos la media de votos de los usuarios, o bien que el usuario simplemente vote la foto tipo menéame y sumemos todos los votos de los usuarios?

**Comment by dcabo** [comment]
Modelo meneame, más sencillo



—

**Comment by rauldiazpoblete** [comment]
Entonces esta gema puede ser una buena opción: https://github.com/ryanto/acts_as_votable. ¿O crees que sería preferible que lo montemos nosotros sin recurrir a ninguna gema?

**Comment by dcabo** [comment]
Si hay gema mejor gema. Aunque parece que así de primeras no parece permitir votar a gente no registrada: ya veremos si hacemos alguna chapuza o si simplemente no permitimos votos anónimos.
