### ISSUE TITLE
Permitir a los usuarios subir sus propias fotos

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#164]

**Comment by rauldiazpoblete** [comment]
El usuario debería introducir un campo de enlace de referencia y deberemos validarlo antes de publicar

**Comment by rauldiazpoblete** [comment]
El interfaz con el botón de upload y su formulario está implementado en https://github.com/civio/quienmanda.es/commit/1ec637733094336d0f870fd13b4469723ae2db22, pero el envío del formulario aún no funciona (me he encontrado con algunos problemas que se me escapan creo que relacionados con el servicio de Amazon S3). Queda pendiente para la vuelta de las vacaciones ;-)
