### ISSUE TITLE
Editor de gráficos personalizados

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#166]
Poder crear un gráfico con una selección de entidades, y que la visualización se pueda embeber en otras páginas.

**Comment by rauldiazpoblete** [comment]
Este issue realmente quedo cerrado en  https://github.com/civio/quienmanda.es/commit/fdd966b3160e9f81980e2054bffd08a36d4c5a4d al permitir embeber gráficos con las acciones realizadas por el usuario sobre él.
