### ISSUE TITLE
Poder ordenar las relaciones de una entidad

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quienmanda.es#168]
La lista de relaciones en la página de una entidad aparece ordenada alfabéticamente, lo cual es bastante inútil, porque muchas de ellas comienzan por el nombre de la entidad que estamos viendo. Hasta que pongamos en marcha una visualización bonita del timeline de cada entidad, quizás podemos ordenar el listado de relaciones (el de debajo del grafo) por fecha, si no es mucho lío. 

ORDEN de arriba a abajo (se me ocurre):
1. Sin campo fecha
1. Sin campo fecha fin
1. De mayor a menor (más nuevo a más antiguo) en la fecha fin.

**Comment by rauldiazpoblete** [comment]
Para que el timeline se vea más claramente hemos ordenado [aquí](https://github.com/civio/quienmanda.es/commit/630a7ddcc01fa344a46e8f88f3dbea9ca28ccfb6) el listado de relaciones de una entidad en base a la fecha 'from' de más antiguo a más reciente. Con ello cerramos este issue por ahora.
