### ISSUE TITLE
'Show foto as header' da error si no hay imagen

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#172]
Hay que asegurarse de que hay una imágen al mostrar la páginas.

(Y es una buena ocasión para cambiar el default de la opción a 'true', que es con diferencia lo más habitual.)

**Comment by rauldiazpoblete** [comment]
Aunque se ha modificado el valor de 'show_photo_as_header' en config/initializers/rails_admin.rb, parece que no tiene efecto en el admin
