### ISSUE TITLE
Año en fecha de los artículos

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quienmanda.es#178]
Que ya llevamos recorrido ;)

**Comment by rauldiazpoblete** [comment]
¿Creéis conveniente añadir el año también en la fecha de los artículos listados en la página Artículos (http://quienmanda.es/posts) o bastaría con añadirlo sólo en los propios artículos ?

**Comment by EvaBelmonte** [comment]
Solo en la página artículos, porque en la página van los más recientes y se entiende bien. Gracias!
