### ISSUE TITLE
Permitir editar los facts

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quienmanda.es#179]
Ahora mismo la única opción, una vez subidos, es eliminar la relación completa. No se puede tocar, por ejemplo, la fuente, que queda fija.

**Comment by caamaledgar** [comment]
Saludos Eva

Pero creo que me mandaste por equivocación este el correo anexo.

Un abrazo, algún día conoceré tu país.

Saludos

2015-01-15 8:58 GMT-06:00 EvaBelmonte <notifications@github.com>:
