### ISSUE TITLE
Compilar automáticamente los ficheros .less

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#181]
Ahora estamos usando Codekit para compilar "a mano" la hoja de estilos, porque Rails soporta Sass, pero no Less por defecto. Empezamos usando Less y añadir [less-rails](https://github.com/metaskills/less-rails) parece sencillo (más sencillo que traducir todo a Sass).

**Comment by rauldiazpoblete** [comment]
Ahora mismo realizar este issue tiene más inconvenientes que ventajas por lo que es preferible seguir trabajando con Codekit. En futuros proyectos si usamos Bootstrap si nos interesa usar ess-rails-bootstrap desde un inicio (http://www.sitepoint.com/twitter-bootstrap-less-and-sass-understanding-your-options-for-rails-3-1/)
