### ISSUE TITLE
Añadir mini-ficha a las caras etiquetadas en las fotos

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#186]
Al pasar el cursor por encima de una cara etiquetada en una foto ahora mismo sólo aparece el nombre, lo cual es bastante pobre. Bastaría con reutilizar la mini-ficha que ya mostramos en la columna de personajes de la derecha.

**Comment by rauldiazpoblete** [comment]
Añadir también link en el nombre de la persona

**Comment by rauldiazpoblete** [comment]
Closed https://github.com/civio/quienmanda.es/commit/276841666b7bff9395df1ba3c4e0b16527120b97

**Comment by dcabo** [comment]
Estupendo



—

**Comment by EvaBelmonte** [comment]
Mola todo. Gracias!  

--  
Eva Belmonte
