### ISSUE TITLE
Bug con plugin Social Share

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#189]

**Comment by dcabo** [comment]
Parece que AddThis ha cambiado algo, y en realidad no aporta nada, parece una buena ocasión para librarse de ello. En La Realidad de la Ayuda hice [esto](https://github.com/dcabo/realidad-ayuda/blob/3ee7d941bdfe260c4ef59fad3462bc9aa126133e/app/views/partials/_socials.html.erb)

**Comment by rauldiazpoblete** [comment]
Closed in https://github.com/civio/quienmanda.es/commit/fbe794157084753efa9a1446e24aadaed1566ce5
