### ISSUE TITLE
Problema de 'adopción' de estilos en la caja de texto de los posts

### ISSUE THREAD

**Issue by EvaBelmonte** [civio/quienmanda.es#192]
Cuando copias el texto desde un word, por ejemplo, adopta los estilos y crea un montón de códigos <span> en el html que desbarajustan todo el texto, a veces incluso solo por párrafos o frases. Lo ideal es que solo cogiera los enlaces y, por defecto, el texto copiado apareciera sin estilo.

**Comment by dcabo** [comment]
No podemos controlar el proceso de copi-pega de Word al editor embebido que tenemos. Lo que sí se puede hacer es seleccionar el texto una vez pegado y darle al boton de borrar estilos de la barra de herramientas, el que se parece a (Tx).

**Comment by EvaBelmonte** [comment]
Pero es que muchas veces crea estilos a lo loco, no solo con el copi-pegado. Y al quitar estilos se va todo al garete y da mucho trabajo, si fuera solo eso no lo habría incluido como issue. Bueno, lo miro con más calma cuando vuelva a pasar y os hago una descripción mas clara, a ver si hay algo que se pueda hacer.
