### ISSUE TITLE
No se distinguen las fichas de personas, artículos y fotos

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#193]
En la página de una persona, como [Rato](http://quienmanda.es/people/rodrigo-rato), o también mucho en los resultados de búsqueda, no es fácil distinguir a primera vista entre lo que son artículos, fotos o entidades. Tienen iconos distintos, y pequeñas diferencias de diseño, pero cuesta verlo.

**Comment by rauldiazpoblete** [comment]
Dado que he tenido que modificar el template de los topics en los resultados de una búsqueda al realizar #214, he probado a modificar el resto de templates en los resultados de una búsqueda, colocando el icono del tipo de elemento (artículo, foto, entidad, topic) arriba y en mayor tamaño de forma que puedan diferenciarse mejor. Aquí tenéis un pantallazo de cómo quedaría (sólo con artículos y un topic) para valorarlo: https://www.dropbox.com/s/0dmgu9t2ihtaxim/Resultados%20para%20Colegio%20del%20pilar%20-%20Qui%C3%A9n%20Manda%20-%20Un%20proyecto%20de%20Civio.png?dl=0

**Comment by EvaBelmonte** [comment]
A mí me gusta, creo que se entiende mejor así, pero no sé si podríamoss establecer criterios de búsqueda tipo: "fotos" o "artículos" y que te muestre solo eso, para ayudar aún más a marcar esas diferencias.

**Comment by dcabo** [comment]
Por mí bien así. Lo de filtrar por tipo en las búsquedas lo tenemos ya en #230, así que podemos hacer el cambio en el diseño que propone Raúl y cerrar esto.

**Comment by rauldiazpoblete** [comment]
Perfecto, voy a aplicar entonces este diseño a personas y organizaciones que aún no lo tienen y lo dejamos cerrado.
