### ISSUE TITLE
Generar fotos cuadradas para protagonistas de Topics

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#204]

**Comment by rauldiazpoblete** [comment]
El tamaño ideal sería 220x220px, y realmente sólo lo necesitaremos para entidades

**Comment by dcabo** [comment]
El cambio en el código afecta a todas las nuevas fotos subidas, pero es necesario generar las fotos cuadradas de entidades ya existentes. Desde la consola de Rails (`rails console`):

```
Entity.find_each do |entity|
  entity.avatar.recreate_versions!(:square) if entity.avatar?
end
```
