### ISSUE TITLE
Cambiar portada eliminando panel de información y añadir slideshow con preview de el último artículo y 2/3 temas

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#205]

**Comment by rauldiazpoblete** [comment]
Basado en http://pgwjs.com/pgwslider/

**Comment by rauldiazpoblete** [comment]
Añadir subtítulo explicativo de Quien Manda sobre el slide

**Comment by EvaBelmonte** [comment]
Un mapa del poder en España, con fuentes verificables y listo para investigar y compartir.
