### ISSUE TITLE
Foto incrustada que no carga

### ISSUE THREAD

**Issue by javidevega** [civio/quienmanda.es#217]
Parece que algunas fotos est'an dando problemas

En este art'iculo, la foto incrustada solo carga a la mitad, as'i que no se ven las labels ni la leyenda 
http://quienmanda.es/posts/quienes-son-los-que-van-a-hacer-cumplir-la-ley-de-transparencia

Adem'as, en esta otra no se cargan las etiquetas>

http://quienmanda.es/photos/321

**Comment by rauldiazpoblete** [comment]
El fallo de la foto incrustada se debe a que no se carga el js del widget: https://d2tvfs931h0imr.cloudfront.net/javascripts/widget/widget.js
Creo que se debe a cómo he añadido el js de widget aquí: https://github.com/civio/quienmanda.es/blob/master/app/views/layouts/widget.html.erb#L68
@dcabo ¿Crees que se debe a la configuración de data-turbolinks-track?

**Comment by dcabo** [comment]
No creo que sea el turbolinks, no. Y el cloudfront ese lo único que hace es pedir ese mismo fichero al servidor. Existe ese javascripts/widget...? Lo hemos movido en algún momento? Pero deberían fallar todas las fotos, no?



—

**Comment by rauldiazpoblete** [comment]
Sí, el widget.js está aquí: https://github.com/civio/quienmanda.es/tree/master/app/assets/javascripts/widget
Éste .js sólo lo necesitamos en las fotos embebidas, lo que no entiendo es por qué no carga

**Comment by dcabo** [comment]
Pero fíjate que lo que está en assets acaba teniendo un nombre de esos raros que pone Rails. No tengo el código delante ahora pero en vez de incluir el nombre del fichero como tal dberíamos usar uno de los métodos de Rails en la vista. No me explico muy bien... :)



—

**Comment by rauldiazpoblete** [comment]
El js está localizado en assets/javascripts/widget/widget.js.
En la vista lo estamos incluyendo con la linea:
<%= javascript_include_tag "widget/widget", "data-turbolinks-track" => true %>
Quizás nos es correcta está linea?

**Comment by dcabo** [comment]
Hmm no sabría decirte. Si ya usamos lo del include tag no sé por qué falla. Lo intento mirar en un rato



—

**Comment by dcabo** [comment]
He corregido lo de la foto incrustada en 0e20cde9c686a26dc1a9182301bca7789673b734. El problema era que en `production.rb`, donde le decimos qué ficheros tiene que precompilar además de `application.js`, habíamos puesto `widget.js`, cuando en realidad el path correcto es `widget/widget.js`.

Lo de la otra foto, la 321, que no mostraba etiquetas, era por otro motivo: la anotación de Urkullu no estaba creada correctamente, imagino que el nombre no coincidía exactamente, y al ser la entidad `nil` el código que genera el JSON petaba. Voy a crear un issue específico para corregir eso bien, de momento he borrado a Urkullu de la foto y ya.
