### ISSUE TITLE
Autocomplete feature for photo annotations doesn't include organizations

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#228]
The autocomplete is using a list of people, instead of entities. Although not very common, [sometimes][1] we need to annotate an organization in a photo, so we should use a list of entities (people+organizations), not people.

[1]: http://quienmanda.es/photos/67

**Comment by rauldiazpoblete** [comment]
Closed in https://github.com/civio/quienmanda.es/commit/b1f82578c146103f979c3f07b03eefc97a867409
