### ISSUE TITLE
Comprobar si podemos usar iframe para embeber fotos

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#237]

**Comment by rauldiazpoblete** [comment]
La única diferencia entre usar el sistema actual para embeber fotos (haciendo uso de pym.js) y usar directamente el iframe, es que en éste último caso no se actualiza el height del iframe al hacer resize:
* [Embed actual](http://rauldiazpoblete.com/demo/test-qm-widget.html)
* [Embed con iframe](http://rauldiazpoblete.com/demo/test-qm-widget-iframe.html)

Existe la posibilidad de actualizar el height del iframe dinámicamente sin hacer uso de pym.js, pero resultaría más complejo porque requiere solventar algunos problemas de cross domain: https://stackoverflow.com/questions/9162933/make-iframe-height-dynamic-based-on-content-inside-jquery-javascript

**Comment by dcabo** [comment]
¿Cómo lo hace Twitter o Youtube? ¿Te obligan a añadir algo en la página 'host', o consiguen hacerlo pegando un iframe y ya? No sé si es posible hacer algo responsive sin modificar el contenedor. Sospecho que es por esto que por ejemplo Infogr.am ofrece dos versiones del código, una con dimensiones fijas y otra responsive, aunque no lo he mirado en detalle.

**Comment by rauldiazpoblete** [comment]
Twitter te añade un script (que es lo que queremos evitar con el iframe) y Youtube te da simplemente un iframe con un width/height definido, por lo que no es responsive.
Efectivamente Infogr.am ejemplifica perfectamente los 2 planteamientos ante los que nos encontramos: ofrecer una versión responsive que te da un div vacío con un script, o bien una versión con un iframe sin script y unas dimensiones fijas

**Comment by dcabo** [comment]
Lo de que no sea responsive parece bastante común: imgur [tampoco lo es](http://imgur.com/blog/2015/05/28/finally-a-cat-tree-theyll-actually-use/).

**Comment by rauldiazpoblete** [comment]
Habilitar una versión iframe con ancho fijo y versión responsive usando script

**Comment by rauldiazpoblete** [comment]
Ahi que comprobar por qué si usamos iframe en lugar de pym.js no se cargan las anotaciones de Annotorious

**Comment by rauldiazpoblete** [comment]
No tiene sentido usar iframe porque nunca sabremos el height del iframe hasta que se haya cargado la foto. Así que descartamos esta opción.
