### ISSUE TITLE
'localhost' hardcodeado en el código del embed

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#253]
En `custom.js`, en la línea 66. Esto se podría sacar del lado Rails, pero posiblemente sea más cómodo y sencillo hacerlo con Javascript a partir de la URL del request. Raúl, tú eso lo controlas más.

**Comment by dcabo** [comment]
¿Puedes sacarlo de la URL del request mejor? Porque si alguien despliega esto en Polonia, por ejemplo, no les va a funcionar...

**Comment by rauldiazpoblete** [comment]
Cierto, no lo había tenido en cuenta
