### ISSUE TITLE
¿Cómo mostramos las relaciones sin inicio/fin en el timeline?

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#254]
Ahora mismo no las mostramos, lo cual es confuso porque a menudo son importantes. Sospecho que la librería que usamos para dibujar el timeline no permitirá hacer demasiadas virguerías de pintar cosas raras al principio/final de la barra, pero Raúl sabra mejor.

Un caso particular son las que no tienen ni inicio ni final, como pueden ser relaciones familiares o de pertenencia entre empresas. ¿Es una barra a todo el ancho una buena opción?

**Comment by EvaBelmonte** [comment]
También tenemos que ver si al pasar por encima queremos que se vea mes/año, como ahora, o día/mes/año. Y si mostramos de alguna manera que está vigente una relación. ¿Ahora se actualiza el 'to' con la fecha actual, @rauldiazpoblete?

**Comment by dcabo** [comment]
Ahora no se actualiza el 'to' porque sólo se muestran las que tienen uno metido, o sea que no tendría sentido. Cuando mostremos las que no tienen 'to' relleno podríamos actualizar con la fecha actual o poner algo en plan 'hasta el presente', que creo se entiende mejor y es más correcto.

**Comment by EvaBelmonte** [comment]
Ojo, en Cañete veo relaciones que están vigentes, como la de comisario > http://quienmanda.es/people/miguel-arias-canete

**Comment by dcabo** [comment]
Ay perdón, que lo he explicado yo mal y estoy liando todo el tema. Ahora recuerdo que Raúl me ha dicho que se ocultan las que no tienen 'from', pero sí se muestran las que no tienen 'to'. ¿Es así, Raúl?

**Comment by rauldiazpoblete** [comment]
Exacto. Buscaré una solución gráfica para poder mostrar todos los casos

**Comment by rauldiazpoblete** [comment]
He mejorado el timeline, formateando las fechas igual que en el curriculum, añadiendo un estilo distinto al final de las barras que llegan hasta la actualidad, y añadiendo eventos puntuales (por ejemplo http://quienmanda.es/people/emilio-botin)

**Comment by rauldiazpoblete** [comment]
No he añadido eventos sin fecha de inicio ni final, puesto que me plantean dudas: no se si tiene sentido visualizar datos atemporales en una gráfica puramente temporal. ¿Qué pasaría con una entidad que sólo tuviese eventos sin fecha de inicio ni fin? No tendría mucho sentido un timeline lleno de barras que no tienen ninguna referencia temporal. Lo comentamos, pero quería dejarlo aquí por escrito ;-)

**Comment by EvaBelmonte** [comment]
Por ahora, excepto que se me escape alguno, las que no tienen ni inicio ni fin son relaciones familiares. Le damos unas vueltas, pero podemos añadir una columna o algún recurso con esas relaciones, quizás. Son muy interesantes en algunos casos

**Comment by dcabo** [comment]
Lo del estilo de relaciones que siguen activas queda muy chulo, estupendo.

¿Soy yo / la caché o se siguen sin mostrar las que no tienen fecha de inicio? Lo digo por Botín, por ejemplo. ¿Tú las ves en local, @rauldiazpoblete?

**Comment by rauldiazpoblete** [comment]
Es cierto, se me olvidó puntalizar que en realidad no muestro ninguna relación que no tenga fecha de inicio. La verdad que no pensaba que se diese este caso, pero puedo solventarlo como las relaciones que siguen activas pero a la inversa.

**Comment by rauldiazpoblete** [comment]
He añadido eventos sin fecha de inicio y sin ninguna fecha en el timeline, para que podamos valorar si nos interesa mostrarlos o no

**Comment by dcabo** [comment]
Es verdad que quedan raras: http://quienmanda.es/people/jose-maria-aznar

**Comment by rauldiazpoblete** [comment]
Precisamente en la APD se da el caso que yo temía, un timeline sin ninguna fecha: http://quienmanda.es/organizations/apd

**Comment by EvaBelmonte** [comment]
Sí, lo he visto. Por eso decía que tenemos que mirarlo con calma, porque la base de datos no se creó pensando en el timeline y tenemos que ajustarlo lo mejor posible para no tener que hacer miles de cambios en los datos. Es difícil, creo. Le damos unas vueltas mañana

**Comment by rauldiazpoblete** [comment]
Perfecto! :)

**Comment by rauldiazpoblete** [comment]
Definitivamente hemos eliminado las relaciones que no tienen fecha de inicio en https://github.com/civio/quienmanda.es/commit/71acd188e657aee2690471832cfc83b566c996a1
