### ISSUE TITLE
Problema con la caché al hacer login

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#262]
Después de loguearse correctamente con twitter, la aplicación no se actualiza mostrando el mensaje de bienvenida en el header y sigue apareciendo el botón de Login

**Comment by dcabo** [comment]
Arreglado en c35b87f380debe3510be8b79bb7856ca45d92c99. Hay que usar `etag` para comprobar si la página sigue siendo válida, en vez de `last_modified`.
