### ISSUE TITLE
No funciona el formulario de subir foto

### ISSUE THREAD

**Issue by rauldiazpoblete** [civio/quienmanda.es#280]

**Comment by EvaBelmonte** [comment]
Acabo de subir una sin problemas desde ese botón, pero estoy logeada como admin, así que no sé si ayuda.
![screen shot 2016-01-28 at 21 41 36](https://cloud.githubusercontent.com/assets/3779304/12658229/0de6a948-c608-11e5-9687-596748bf52b5.png)

**Comment by rauldiazpoblete** [comment]
Perdona @EvaBelmonte , este issue era un apunte mío para la versión del nuevo diseño. Ya está corregido en https://github.com/civio/quienmanda.es/commit/eb16c492e81060cc5761caf83780d0b4e7d7e9e7
