### ISSUE TITLE
Visualización de curriculum/bio como timeline

### ISSUE THREAD

**Issue by dcabo** [civio/quienmanda.es#86]
No tengo clara la granularidad:
- queremos un timeline de los cargos de una persona? (pueden superponerse)
- o queremos un timeline de sus reuniones, reconstruidas via crowdsourcing o lo que sea

En cualquier caso posiblemente sea después del Día 1, porque no tendremos tal vez toda la info de fechas y similares

[Un ejemplo interesante][1]. [Otros][2] [dos][4] de Cargografías. Y una librería interesante, [Timesheet.js][3].

[1]: http://interactive.zeit.de/bundeskabinett/#/merkel-ii/5
[2]: http://www.cargografias.org/cargografia/presidenciables-chile
[3]: http://sbstjn.github.io/timesheet.js/
[4]: https://twitter.com/Cargografias/status/578363219951095808

**Comment by rauldiazpoblete** [comment]
Otro ejemplo de Cartografías http://www.cargografias.org/#/nombre-2001-12-8-7-6-5-685

**Comment by rauldiazpoblete** [comment]
Integrar Timesheet.js (https://sbstjn.github.io/timesheet.js/) para valorar como queda. Hacerlo visible solo si estas logueado para poder verlo todos en producción sin que se haga público

**Comment by rauldiazpoblete** [comment]
Implementado en https://github.com/civio/quienmanda.es/commit/e4b46ce4934391701949dfc505ef49cdb006d8c1
Faltaría valorar qué hacer en casos en que no tenemos fecha de inicio o cómo resaltar las relaciones que están actualmente vigentes

**Comment by rauldiazpoblete** [comment]
Las relaciones vigentes se resaltan en las mejoras en https://github.com/civio/quienmanda.es/commit/ae7e546f038d19bf4959e92ea39e67deb05219dd.
En #254 se comenta como mostrar relaciones sin inicio/fin
